// let now = new Date();
// console.log(now);
// console.log(now.getFullYear());
// console.log(now.getMonth());
// console.log(now.getDay());
// console.log(now.getHours());
// console.log(now.getMinutes());
// console.log(now.getSeconds());
let now = new Date("2024-12-18");
console.log(now);
console.log(now.getFullYear());
console.log(now.getDate());
console.log(now.getDay());
console.log(now.getMonth());

let n = new Date("2024-12-16");
console.log(n);
console.log(n.getFullYear());
console.log(n.getDate());
console.log(n.getDay());
console.log(n.getMonth());
